# Use official Node.js image
FROM node:24-alpine

# Set working directory
WORKDIR /app

# Copy only package.json and package-lock.json first
COPY package*.json ./

# Install dependencies (bcrypt se compila para Linux aquí)
RUN npm install

# -------------------------------
# Agregar entrada al /etc/hosts
# -------------------------------

RUN sh -c 'echo "10.0.10.16 srvgfe.grep.local" >> /etc/hosts'
# -------------------------------

# Copy the rest of the app (no node_modules)
COPY . .

# Optional: create data directory
RUN mkdir -p /mnt/data

# Use the port from Azure Container Apps env variable
ENV PORT=5000

EXPOSE $PORT

# Start the app
CMD ["npm", "start"]